name: Fuzz Parser

on:
  push:
    branches: [main, master]
    paths:
      - grammar.js
      - src/parser.c
  pull_request:
    paths:
      - grammar.js
      - src/parser.c
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Fuzz parser
        uses: tree-sitter/fuzz-action@v4
        with:
          language: opam
